# Generated by Django 6.0.4 on 2026-05-03 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_tests', models.IntegerField()),
                ('passed', models.IntegerField()),
                ('failed', models.IntegerField()),
                ('raw_logs', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255)),
                ('error_message', models.TextField()),
                ('stack_trace', models.TextField(blank=True)),
                ('category', models.CharField(max_length=100)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='analyzer.testresult')),
            ],
        ),
    ]
